### ISSUE TITLE
[ENHANCEMENT] Community Support

### ISSUE THREAD

**Issue by firegrass** [Smana/demo-cloud-native-ref#250]
### Community Support

We are starting to adopt this work as a starting point for our k8s infra. I'm wondering if there's anyone else in the same situation and might benefit from a slack (or similar) to discuss issues and share advice.

**Comment by Smana** [comment]
Hey @firegrass ,
I'm glad to see this project has been helpful for you! I created it as a booster for starting a platform. Currently, I am the sole maintainer, but I am completely open to building a community around this work.

**Comment by firegrass** [comment]
Thanks @Smana

I'll start adding some Issues, we'll see how it goes :smile:

**Comment by Smana** [comment]
Great, let's do that!
