### ISSUE TITLE
Gateway API and EKS (recent regression): upstream connection timeout

### ISSUE THREAD

**Issue by Smana** [Smana/demo-cloud-native-ref#251]
Issue being followed in Cilium repositiory https://github.com/cilium/cilium/issues/32616.

**Comment by Smana** [comment]
Seems to be caused by the latest version of Bottlerocket.

**Comment by firegrass** [comment]
I can confirm moving to `AL2` amis resolves this issue.

**Comment by Smana** [comment]
Thanks @firegrass , fixed by https://github.com/Smana/demo-cloud-native-ref/pull/254
